---

# https://docs.travis-ci.com/user/osx-ci-environment

matrix:
  include:
    # macOS 10.13
    - os: osx
      osx_image: xcode9.3beta
    # macOS 10.12
    - os: osx
      osx_image: xcode8.3
    # macOS 10.11
    - os: osx
      osx_image: xcode7.3
    # macOS 10.10
    - os: osx
      osx_image: xcode6.4
  allow_failures:
    # macOS 10.12
    - osx_image: xcode8.3
    # macOS 10.10
    - osx_image: xcode6.4
  fast_finish: true

install:
  - bash scripts/install_deps.sh
  - bash scripts/create_fork_files.sh
  - ansible-galaxy install -r requirements.yml --force

script:
  # Playbook syntax check
  - ansible-playbook macsible.yml --syntax-check
  # Run Ansible playbook:
  # - Skip tasks/roles that we know cause issues in Travis
  - ansible-playbook macsible.yml --skip-tags "no_ci"
