---

quick_look_plugins_list:
  - betterzipql
  - qlcolorcode
  - qlmarkdown
  - qlprettypatch
  - qlstephen
  - quicklook-csv
  - quicklook-json
  # - suspicious-package # TODO: Fails build
  - webpquicklook
