---

- name: Install Steam
  homebrew_cask: name=steam state=present
  notify: brew cask cleanup

# Relocate & symlink Steam's "Application Support" directory.

- name: Remove default Steam directrory prior to creating symlink
  file:
    path: "~/Library/Application Support/Steam"
    state: absent
  when: steam_symlink_src != ""

- name: Create symlink for Steam directory
  file:
    path: "~/Library/Application Support/Steam"
    src: {{ steam_symlink_src }}
    state: link
    force: yes
  when: steam_symlink_src != ""
