---

# Homebrew
- name: brew cleanup
  command: brew cleanup

# Restarts a bunch of OS X apps & processes
- name: killall
  command: killall "{{ item }}" > /dev/null 2>&1
  with_items:
    - cfprefsd
    - Dock
    - Finder
    - SystemUIServer
  ignore_errors: yes

- name: killall cfprefsd
  command: killall "cfprefsd"
  ignore_errors: yes

- name: killall Dock
  command: killall "Dock"
  ignore_errors: yes

- name: killall Finder
  command: killall "Finder"
  ignore_errors: yes

- name: killall SystemUIServer
  command: killall "SystemUIServer"
  ignore_errors: yes

- name: killall Terminal
  command: killall "Terminal"
  ignore_errors: yes
