---

atom_upgrade_packages: false

atom_packages:
  - afterglow-monokai-syntax
  - atom-beautify
  - autoclose-html
  - autocomplete-plus
  # - autocomplete-sass # TODO: Currently failing on installation
  - bottom-dock
  - double-tag
  - emmet
  - file-icons
  - git-plus
  - git-time-machine
  - grunt-manager
  - gulp-manager
  - highlight-line
  - highlight-selected
  - isotope-ui
  - language-ansible
  - language-patch
  - linter
  - linter-ansible-linting
  - linter-manager
  - open-terminal-here
  - pigments
  - project-manager
  - sort-lines
  - split-diff
  - svg-preview
  - todo-manager
  - travis-ci-status
