---

# Filenames must include .app extension.
login_items_apps:
  - Alfred 3.app
  - aText.app
  - BetterTouchTool.app
  - CrasPlan menu bar.app
  - Dropbox.app
  - Flux.app
  - Google Photos Backup.app
  - HazelHelper.app
  - Keyboard Maestro Engine.app
  - Moom.app
  - Path Finder.app
