---

- name: Install Evernote
  homebrew_cask: name=evernote state=present
  environment:
    HOMEBREW_CASK_OPTS: --appdir={{ cask_app_appdir }}
  notify: brew cask cleanup

- name: "Beta: Enable code block"
  command: defaults write com.evernote.Evernote ENEnabledBetaFeatures -array "CodeBlock"
#   osx_defaults:
#     domain: com.evernote.Evernote
#     key: ENEnabledBetaFeatures
#     type: array
#     value: ["CodeBlock"]
  notify:
    - killall Evernote
