---

# - List order will effect order in Dock
# - Filenames must include .app extension
# - Works with any type of app:
#   - App Store app
#   - Cask app
#   - System app
dock_apps:
  - Path Finder.app
  - Dash.app
  - Skype.app
  - Slack.app
  - Google Chrome.app
  - Evernote.app
  - Skitch.app
  - Calendar.app
  - PhpStorm.app
  - Atom.app
  - Wunderlist.app
  - System Preferences.app
  - xScope.app
  - Tower.app
  - Transmit.app
  - Sequel Pro.app
  - Parallels Desktop.app
  - VirtualBox.app
