---

- name: "{{ item.name }}"
  osx_defaults:
    domain: com.apple.Safari
    key: "{{ item.key }}"
    type: bool
    value: "{{ item.value }}"
  with_items:
    - { name: "Don't send search queries to Apple", key: "UniversalSearchEnabled", value: "false"}
    - { name: "Don't send search queries to Apple", key: "UniversalSearchEnabled", value: "true"}
    - { name: "Show the full URL in the address bar (note: this still hides the scheme)", key: "ShowFullURLInSmartSearchField", value: "true"}
    - { name: "Prevent Safari from opening ‘safe' files automatically after downloading", key: "AutoOpenSafeDownloads", value: "false"}
    - { name: "Allow hitting the Backspace key to go to the previous page in history", key: "com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled", value: "true"}
    - { name: "Hide Safari's bookmarks bar by default", key: "ShowFavoritesBar", value: "false"}
    - { name: "Hide Safari's sidebar in Top Sites", key: "ShowSidebarInTopSites", value: "false"}
    - { name: "Enable Safari's debug menu", key: "IncludeInternalDebugMenu", value: "true"}
    - { name: "Make Safari's search banners default to Contains instead of Starts With", key: "FindOnPageMatchesWordStartsOnly", value: "false"}
    - { name: "Enable the Develop menu and the Web Inspector in Safari (1)", key: "IncludeDevelopMenu", value: "true"}
    - { name: "Enable the Develop menu and the Web Inspector in Safari (2)", key: "WebKitDeveloperExtrasEnabledPreferenceKey", value: "true"}
    - { name: "Enable the Develop menu and the Web Inspector in Safari (3)", key: "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled", value: "true"}
  notify:
    - killall

- name: Set Safari's home page to `about:blank` for faster loading
  command: defaults write com.apple.Safari HomePage -string "about:blank"
  notify:
    - killall

- name: Disable Safari's thumbnail cache for History and Top Sites
  osx_defaults:
    domain: com.apple.Safari
    key: DebugSnapshotsUpdatePolicy
    type: int
    value: 2
  notify:
    - killall

- name: Remove useless icons from Safari's bookmarks bar
  command: defaults write com.apple.Safari ProxiesInBookmarksBar "()"
  notify:
    - killall

- name: Add a context menu item for showing the Web Inspector in web views
  osx_defaults:
    domain: NSGlobalDomain
    key: WebKitDeveloperExtras
    type: bool
    value: true
  notify:
    - killall

# Privacy: don't send search queries to Apple
# defaults write com.apple.Safari UniversalSearchEnabled -bool false
# defaults write com.apple.Safari SuppressSearchSuggestions -bool true

# Show the full URL in the address bar (note: this still hides the scheme)
# defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true

# Set Safari's home page to `about:blank` for faster loading
# defaults write com.apple.Safari HomePage -string "about:blank"

# Prevent Safari from opening ‘safe' files automatically after downloading
# defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

# Allow hitting the Backspace key to go to the previous page in history
# defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool true

# Hide Safari's bookmarks bar by default
# defaults write com.apple.Safari ShowFavoritesBar -bool false

# Hide Safari's sidebar in Top Sites
# defaults write com.apple.Safari ShowSidebarInTopSites -bool false

# Disable Safari's thumbnail cache for History and Top Sites
# defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2

# Enable Safari's debug menu
# defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

# Make Safari's search banners default to Contains instead of Starts With
# defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

# Remove useless icons from Safari's bookmarks bar
# defaults write com.apple.Safari ProxiesInBookmarksBar "()"

# Enable the Develop menu and the Web Inspector in Safari
# defaults write com.apple.Safari IncludeDevelopMenu -bool true
# defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
# defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

# Add a context menu item for showing the Web Inspector in web views
# defaults write NSGlobalDomain WebKitDeveloperExtras -bool true
